version: '3'

services:
  oaks-reverse-proxy:
    image: nginx:alpine
    ports:
      - "80:80" # Expose port 80 on the host to the Nginx container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1
      - web2

  web1:
    image: node:alpine
    command: sh -c 'npx -y serve -p 3001'
    volumes:
      - ./smoothkitties.com:/home/node/app
    working_dir: /home/node/app

  web2:
    image: node:alpine
    command: sh -c 'npx -y serve -p 3002'
    volumes:
      - ./site1.smoothkitties.com:/home/node/app
    working_dir: /home/node/app